import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import 'primereact/resources/themes/lara-light-indigo/theme.css';  
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

import './globals.css'
import Footer from "../components/footer"
import Header from '../components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
    <>
      <Header/>

        <html lang="en">

          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            
            {children}

          </body>
          


        </html>

      <Footer />
    </>

  )
}